name: Release and Publish Packages

on:
  push:
    branches:
      - master

jobs:
  # test:
  #   name: Run unit tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository
  #       uses: actions/checkout@v2
  #     - name: Setup NodeJS
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 18
  #     - name: Install node dependencies
  #       run: npm ci
  #     - name: Run tests
  #       run: npm test

  release:
    name: Create release and publish
    # needs: test
    if: github.repository == 'brainbits/eslint-config-brainbits'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Install node dependencies
        run: npm ci
      - name: Release and publish using lerna with conventional commits
        env:
            NODE_AUTH_TOKEN: ${{secrets.npm_token}}
        run: |
            git config --global user.name 'Brainbits Bot'
            git config --global user.email 'info@brainbits.net'
            npx lerna publish --conventional-commits --conventional-graduate --yes
